### ISSUE TITLE
GEDCOM X?

### ISSUE THREAD

**Issue by justincy** [todrobbins/awesome-gedcom#3]
Libraries which only support [GEDCOM X](http://www.gedcomx.org/) and not GEDCOM seem out of place in this repo. If that's true, I recommend removing the following libraries:

* gedcomx-date-js
* gedcomxjs
* gedcomx-python

**Comment by todrobbins** [comment]
Good point, @justincy. I'll remove those for now.

**Comment by todrobbins** [comment]
PS: I think you're right that the convertor from GEDCOM to GEDCOM X is relevant, but the others are specifically for manipulating GEDCOM X data structures.
