### ISSUE TITLE
GEDCOM parser for R

### ISSUE THREAD

**Issue by jl5000** [todrobbins/awesome-gedcom#8]
Hi, 

I have a package for R that works with GEDCOM files (still under development): https://jl5000.github.io/tidygedcom/

**Comment by todrobbins** [comment]
@jl5000 that link isn't loading for me 😢

Are you still working in this package?

**Comment by todrobbins** [comment]
Nevermind, I found it! https://jl5000.github.io/tidyged/

Let's get this added!

**Comment by todrobbins** [comment]
✅ [Added](https://github.com/todrobbins/awesome-gedcom/commit/207adea2a3183bc30feda483421aa513263948e8)
